id = "cython"
name = "Cython"
version = "0.1.1"
schema_version = 1
authors = ["Lukas Geiger <lukas.geiger94@gmail.com>"]
description = "Cython language support for Zed"
repository = "https://github.com/lgeiger/zed-cython"

[grammars.cython]
repository = "https://github.com/b0o/tree-sitter-cython"
commit = "5f5468af68899b1013eef19ffe154e3f9c7a5d4a"
